services:
  accounts:
    image: "joheiss/sb3-accounts:v1"
    container_name: "jo_accounts"
    ports:
      - "8091:8091"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - jovisco

  loans:
    image: "joheiss/sb3-loans:v1"
    container_name: "jo_loans"
    ports:
      - "8092:8092"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - jovisco

  cards:
    image: "joheiss/sb3-cards:v1"
    container_name: "jo_cards"
    ports:
      - "8093:8093"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - jovisco

networks:
  jovisco:
    driver: "bridge"

