@baseUrl = http://localhost:8091
@accountsUrl = {{baseUrl}}/api/v1/accounts

# GET health
GET {{baseUrl}}/actuator/health

###

# Refresh config using cloud bus via actuator
POST {{baseUrl}}/actuator/busrefresh

###

# Refresh config using actuator
POST {{baseUrl}}/actuator/refresh

###

# GET build version
GET {{accountsUrl}}/version

###

# GET java version
GET {{accountsUrl}}/java-version

###

# GET env variable
GET {{accountsUrl}}/env-variable/SPRING_PROFILES_ACTIVE

###

# GET contact information
GET {{accountsUrl}}/contact-info

###

# GET customer & account data by mobile number
GET {{accountsUrl}}/+49171123456789
# POST create a customer and an account

###
POST {{accountsUrl}}
Content-Type: application/json

{
    "name": "Hansi Hackl",
    "email": "hansi@hackl.de",
    "mobileNumber": "+49171123456789"
}

###
PUT {{accountsUrl}}
Content-Type: application/json

{
  "customer": {
    "name": "Hansi Hacklhuber",
    "email": "hansi@hackl.de",
    "mobileNumber": "+49171123456789"
  },
  "account": {
    "id": 1350172270,
    "type": "Savings",
    "branchAddress": "Hintere Schmutzgasse 1, Bauernhäusl"
  }
}

###

# Delete an account by mobile number
DELETE {{accountsUrl}}/+49171123456789

###

###
POST {{accountsUrl}}
Content-Type: application/json

{
    "name": "Email und Mobile falsch",
    "email": "hansi@hackl.de",
    "mobileNumber": "+491711923456789"
}
###

POST {{accountsUrl}}
Content-Type: application/json

{
}
###
PUT {{accountsUrl}}
Content-Type: application/json

{
  "customer": {
    "name": "Hansi Hackl",
    "email": "hansi@hackl.de",
    "mobileNumber": "+49171123456789"
  },
  "account": {
    "id": 1697082356,
    "type": "Savings",
    "branchAddress": "321 Sub Street, Hungtington Beach"
  }
}
###
PUT {{accountsUrl}}
Content-Type: application/json

{
  "customer": {
    "name": "Hansi Hackl",
    "email": "hansi@hackl.de",
    "mobileNumber": "+49171123456789"
  },
  "account": {
    "type": "Savings",
    "branchAddress": "321 Sub Street, Hungtington Beach"
  }
}
###

PUT {{accountsUrl}}
Content-Type: application/json

{
  "customer": {
  },
  "account": {
  }
}
###